### ISSUE TITLE
The define_profiles script misses some isolates

### ISSUE THREAD

**Issue by jgugliel** [kjolley/BIGSdb#331]
Hi Keith, Julien here.

I ran into a strange issue. A user wanted to erase previously attributed STs for a specific scheme and run again the define_profiles script with new parameters. I used the interface to delete all the STs.

He then ran the script again, using a missing alleles threshold of 50. The problem is that some isolates are skipped by the script. These isolates are below the defined threshold, with only one or two missing alleles. They are not new isolates, and they correctly received a ST when the script was used the first time (months ago).

I thought that maybe there was something wrong with the deleted STs. So I created another scheme, with the exact same members than the previous one.
I ran the script, and the exact same isolates have been skipped.

Have you got any idea of what's going on ?

Thanks a lot

**Comment by kjolley** [comment]
Hi Julien,
I have seen a similar issue. It could be that you have already defined a similar profile but the missing loci may be causing the problem. For example a 10 locus scheme that allows 2 missing loci:

4,8,4,8,3,2,5,7,3,3 : defined first as ST-1.
then
4,8,4,8,3,2,N,7,3,3 (the same but missing locus 7): cannot be assigned a new ST because N=any, and this would be the same as ST-1 in comparisons, but the isolate cannot be assigned as ST-1 as this is defined with a value for locus 7 (even though the isolate is below the threshold of allowed missing loci).

If you use the

**Comment by jgugliel** [comment]
Ok I understand.

This user faces this situation for 174 out of 1274 isolates... which is quite a lot ! Is there anything that can be done to avoid that ?

The only thing i can think of would be to reset the profiles, then define them only for the problematic isolates, and finally for all the others...

**Comment by kjolley** [comment]
I suppose if your isolate clustering is more important than your cgMLST nomenclature, then we could modify the script (as an option) so that profiles can be defined unless they are exact (treating N as a specific allele). This would then define a cgST for every isolate if it had fewer missing loci than the threshold. The problem with this is that many isolates without missing data could end up with multiple cgSTs - I don't think this is particularly desirable.  

Presumably this is an issue that will improve as data gets better. If the scheme is core, then you should be identifying most loci - is it a case that some new alleles haven't yet been assigned?

**Comment by jgugliel** [comment]
But this was the case in previous versions, right? I mean, I've seen export tables generated with older versions of BIGSdb showing multiples STs per isolates. I found that weird in the beginning, but looking closely I understood that this was due to the way missing alleles were treated. I wrote a short note to 'my' users to clarify that, and I had to update one of my scripts to deal with those situations.

> Presumably this is an issue that will improve as data gets better

Yes, I agree.

> If the scheme is core, then you should be identifying most loci

It's core for 95% of the strains we used to define the core :)

> is it a case that some new alleles haven't yet been assigned?

I'm sorry, what do you mean?

**Comment by kjolley** [comment]
But those STs weren't defined by this script. You can have isolates with multiple STs if they have multiple hits for a locus (perhaps due to a mixed culture), but that is not the same as assigning STs that have the same profile as another ST with the exception of a missing locus (that has never been allowed - this is checked for when uploading new ST definitions).

What I meant by the last comment was, if you scan the genome manually, do you find new alleles that have yet to be given an allele number? i.e. have they been incompletely curated?  Or is the locus completely missing from the assembly?

**Comment by jgugliel** [comment]
I just realized that I messed up things in my head. I did not observed multiple STs assigned to single isolates, but multiple groups (with the cluster.pl script). My bad.

The isolates have been completely curated, as far as I can tell. I'll discuss the pros and cons of treating missing loci as specific alleles with the users. Personally I think you're right, multiple STs could lead to undesirable situations.

Thanks for the help !

**Comment by jgugliel** [comment]
Sorry, actually I was right. An isolate that in a previous run was assigned a ST now gets none. And an some isolates were assigned mutliple STs, but not because of multiple hits for a locus since now a single ST is assigned to them.

I just compared an old export table with the current one, and the profiles are exactly the same, but the ST are different.

I guess that these changes will affect the clustering (with the cluster.pl script) ?

**Comment by kjolley** [comment]
OK. I guess this is the change introduced with https://github.com/kjolley/BIGSdb/commit/1c6305489f84d65263089dad12161336f0a2963c. Sorry.

**Comment by jgugliel** [comment]
Ok I see.
The previous version of the script worked fine to me, at least from this ST versus missing loci point of view. But I understand that it could lead to undesirable outcomes. Maybe the old behavior can be introduced, as you suggested, as an option?

**Comment by kjolley** [comment]
Hi Julien,

Try https://github.com/kjolley/BIGSdb/commit/116162458bf430f51fb6741541f7d03b851b5e4a using the --match_missing option.

Best wishes
Keith
