### ISSUE TITLE
Argument "" isn't numeric in sort at /usr/local/lib/BIGSdb/Plugins/Export.pm line 616

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#536]
Hi,

We are experiencng some timeout when exporting datasets of 1500 isolates and more. When looking at the log, they are full of 
```
[Fri Nov 23 10:38:35 2018] [error] [client xxx.xx.xxx.xx] Argument "" isn't numeric in sort at /usr/local/lib/BIGSdb/Plugins/Export.pm line 616., referer: https://bigsdb-dev.web.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_isolates&page=query&l=1
[Fri Nov 23 10:38:35 2018] [error] [client xxx.xx.xxx.xx] Argument "" isn't numeric in sort at /usr/local/lib/BIGSdb/Plugins/Export.pm line 616., referer: https://bigsdb-dev.web.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_isolates&page=query&l=1
[Fri Nov 23 10:38:35 2018] [error] [client xxx.xx.xxx.xx] Argument "" isn't numeric in sort at /usr/local/lib/BIGSdb/Plugins/Export.pm line 616., referer: https://bigsdb-dev.web.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_isolates&page=query&l=1
[Fri Nov 23 10:38:35 2018] [error] [client xxx.xx.xxx.xx] Argument "" isn't numeric in sort at /usr/local/lib/BIGSdb/Plugins/Export.pm line 616., referer: https://bigsdb-dev.web.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_isolates&page=query&l=1
```

This logs are slowing done the process causing the timeout.

After some research, i found that `allele_id_format` indicate that the allele id is an integer, but is probably not:
```sql
select id , data_type,allele_id_format,dbase_id from loci limit 1;
   id    | data_type | allele_id_format | dbase_id 
---------+-----------+------------------+----------
 lmo2204 | DNA       | integer          | lmo2204
(1 ligne)
```
What suprise me is that this field is not new and, to the best of my knowledge, it has not been updated on our side recently.

Could you indicate us how how to specify that the allele_id_format is not an integer ?

Is `allele_id_format` really the cause of the `Argument "" isn't numeric` problem ?

Thanks for your help
Bryan

**Comment by kjolley** [comment]
You can set this to 'text' - if you edited the loci table in the web interface you would see that the dropdown list of allowed values is only 'integer' and 'text'.

However, normally your allele ids should be integers - setting it to text will cause you problems (it won't be able to suggest the next available id, and you will find that 3 > 10 when searching by allele_id as it will use alphabetical searches. Looking at your database online I see that all the defined alleles for lmo2204 are integer ids. I think your problem is that in your allele_designations table (in the isolate database) you have some values with an allele_id of an empty string "". I don't know how this would have occurred but I have had a similar issue in the past so I suspect there was a bug in an earlier version that allowed this. Check the allele_designations table for this and remove any entries with a blank allele_id.

**Comment by bryan-brancotte** [comment]
Hi

It seems that 
>On our side, empty allele_id is usual when a CDS is absent/uncomplete.

Could we find a way of being more resilient ? Maybe the sorting criteria could be something like 
```perl
sort { $a eq "" ? 1 : $b eq "" ? -1 : $a <=> $b }
```

I have just done a PR, if can be of any help.

Best regards

**Comment by kjolley** [comment]
No, you should never have an empty allele_id. It's meaningless to define an allele designation with an empty value - this should not happen.

**Comment by kjolley** [comment]
Could you do the following please:
`SELECT MAX(datestamp) FROM allele_designations WHERE allele_id="";`

We need to find out why and when this happened.

**Comment by bryan-brancotte** [comment]
```sql
SELECT count(allele_id), MIN(datestamp), MAX(datestamp) FROM allele_designations WHERE allele_id = '';
 count | min | max 
-------+-----+-----
     0 |     | 
(1 ligne)
```

Now I do not understand anymore why we get these `Argument "" isn't numeric`

**Comment by kjolley** [comment]
OK. I see the problem. Line 623 creates an empty string rather than an empty list if there are no alleles. Fix coming.

**Comment by kjolley** [comment]
This fix breaks functionality. It actually misses a column with no allele designation so columns become misaligned.
