### ISSUE TITLE
Timeout when importing ne sequences in seqdef db

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#568]
We have deported computation on a cluster, which (can) induce delay. Users have reported timeout when trying to upload 70 sequences. On of the problem is that our web server had a timeout of 60s, we changed it, but it cannot solve entirely the problem.

We would have a feature request:
> make the script running data validation reporting back on each line processed. This will void the Timeout and makes the web server wait for many longer for the whole dataset to be processed.

or/and
> make the Batch imports as a job, and allow us to define the threshold in bigsdb.conf accordingly to out infrastructure.

Thanks for your help !

**Comment by kjolley** [comment]
I think the best way for me to do this is to refactor the code so that the sequence checks are performed by a separate module that can be called by a forked process. The web page can then fully load (so won't time out) and then will update by an AJAX call that polls looking for a results file. This is the way that the sequence query now works.
