### ISSUE TITLE
GrapeTree and PhyloViz issues with calculating distances

### ISSUE THREAD

**Issue by alejocrojo09** [kjolley/BIGSdb#612]
Hello, I have a question regarding GrapeTree and PhyloViz. For the moment I am using BIGSdb to have an isolate database with data records and 16S sequences from different bacteria. For sequence definition database I have my own curated database of 16S. I for several sequence bins, I have already tag the sequences with the alleles from the sequence definition database. Even I manually added the allele profiles for the isolate databases. When I use PhyloViz and GrapeTree to compare several isolates 16S sequences, the distances for Newick tree are alway for each isolate 1, getting straight lines connected to a root which this does not make sense. Am I doing wrong something with these plugins? Am I not implementing well the tagging for the sequences bin?

Thank you for your attention

**Comment by kjolley** [comment]
BIGSdb is designed primarily for gene-by-gene analysis, i.e. using allelic profiles rather than sequences directly. Both GrapeTree and PhyloViz also work at the level of allelic profile. Since, in this case, your allelic profiles use a single locus, your pairwise comparisons have two possible distances - 0 if they have the same allele, or 1 if they have a different allele. Therefore, what you are seeing is expected behaviour.

These analyses are meant for MLST-like schemes, especially cgMLST where you will have 1000+ loci, and a simple count of the number of loci that are different between isolates is informative.
