### ISSUE TITLE
[API] Missing resources in /db

### ISSUE THREAD

**Issue by TheBready** [kjolley/BIGSdb#639]
Hello,

first of all thanks for developing the API and providing access to PubMLST.
I am trying to get all cgMLSTs over the API and I noticed that not every resource is listed in db/.

**Expected**: 
http://rest.pubmlst.org/db/pubmlst_escherichia_seqdef is available and is listed in http://rest.pubmlst.org/db.

**Actual**:
http://rest.pubmlst.org/db/pubmlst_escherichia_seqdef is not listed in http://rest.pubmlst.org/db.

I am using /db to get all available resources, but because not everything is listed I miss some.
Am I doing something wrong or is there another way to get all resources?

**Comment by kjolley** [comment]
Hi,

There was no good reason that this wasn't listed. I have now added it.

The actual reason is that this database existed on our system long before we decided to make it public - it was used for some internal projects. PubMLST is not the authoritative server for the E. coli schemes (these come from Enterobase) but we had a synchronized copy that we had for internal use. We did later decide to make an Escherichia database available but it never got added to the RESTful API index (until now).
