### ISSUE TITLE
Error: "The defined labelfield 'isolate' does not exist in the database. Please set the labelfield attribute in the system tag of the database XML file"

### ISSUE THREAD

**Issue by JafarAkhondali** [kjolley/BIGSdb#681]
Hello,
First of all, thank you for putting SO MUCH effort into developing this software.

I just wanted to add a new isolate, and here is what I get in logs:
```
2020/04/09 03:13:45 [ERROR] ::1 Application.pm:261  - The defined labelfield 'isolate' does not exist in the database. Please set the labelfield attribute in the system tag of the database XML file.
2020/04/09 03:13:45 [WARN] ::1 Datastore.pm:2304  - DBD::Pg::st execute failed: execute called with an unbound placeholder at /usr/local/lib/BIGSdb/Datastore.pm line 2303.
2020/04/09 03:13:45 [WARN] ::1 Datastore.pm:2304  -  Query:SELECT EXISTS(SELECT * FROM isolates WHERE id=?) at /usr/local/lib/BIGSdb/CurateAddPage.pm line 1024.
```

Another thing is in my "Add new isolates" page, some fields like Id should be automatically present, right?!
![image](https://user-images.githubusercontent.com/11364402/78840763-e350a500-7a10-11ea-97c7-42ba767e3ce5.png)
Is this normal? or everything(including Id) should be added in database config.xml? How should we keep track of this Id field? why not making it auto increment?

**Comment by kjolley** [comment]
No, this isn't normal. The fields defined in the config.xml that comes with the package (https://github.com/kjolley/BIGSdb/tree/develop/xml) are the minimum fields required. You can add to these, but you must include id, isolate, sender, curator, date_entered and datestamp. The 'isolate' field can be renamed if required, e.g. to 'strain' - you would need to set the labelfield attribute in the system tag if you do this.

You do not need to keep track of id. The software automatically fills in the next available id number. It is not auto-incrementing (at the database level) because sometimes you may wish to override the selected id (for reserving contiguous blocks of id numbers for example).

Some of the decisions made about the format of the xml file are inherited from the previous generation MLST software (https://www.ncbi.nlm.nih.gov/pubmed/15230973) and even back to the first generation (https://www.ncbi.nlm.nih.gov/pubmed/11724739).

**Comment by JafarAkhondali** [comment]
Oh, I missed these files at [https://github.com/kjolley/BIGSdb/tree/develop/xml](https://github.com/kjolley/BIGSdb/tree/develop/xml). Thank you for clarification.

Is it mentioned in docs? if yes, close the issue please :pray:

**Comment by kjolley** [comment]
I have added clarification to the documentation so that hopefully this is now clearer (https://github.com/kjolley/BIGSdb_documentation/commit/ada821648dbb5baf53d9b2222b47025996e4952e).
