### ISSUE TITLE
changing status from public to private

### ISSUE THREAD

**Issue by jfmarietpro** [kjolley/BIGSdb#804]
Dear Keith,
I would need your help.
I recently lost the status of private for some isolates.
In the past (I don't know which version) it was only necessary to link data to a private project to render them private.
I seems that's not anymore possible.
Have you any idea how to solve this?
Reagards
JF Mariet (https://bigsdb.pasteur.fr/leptospira/)

**Comment by jfmarietpro** [comment]
Dear Keith, 
Thank for your fast reply I really appreciate.
I was wondering if there was a way in BIGSdb to make sure that public data can be rendered private.
I will see with our adminitrator to apply your recommandation.
Than you very much for your help.

**Comment by kjolley** [comment]
That wasn't a recommendation. That was an example of how data could be made private using a bit of a database hack (and probably how it was set up at Pasteur) - it also requires setting up a separate database configuration that allows you to view the private data, so it's overly complicated. We used to use this on PubMLST but are trying to move away from it as it causes problems (users don't always understand what the field is for and decide to enter arbitrary values in it, then wonder why they cannot access their data).

BIGSdb does now properly support private data so it should no longer be necessary to use the method I mentioned. See https://bigsdb.readthedocs.io/en/latest/private_records.html. However, this assumes that you upload data as private. At the moment, there is no way to make a public record private via the web interface using the supported method of private data. In order to do this, somebody would need to manually enter values in the private_isolates table. This table contains isolate_id and user_id columns - adding values in here to link an isolate_id to a user_id will render the isolate record private, accessible only to the user. The isolate record can be made visible to others by the user creating a project, adding the record to the project, and then sharing access to the project to other named accounts.

**Comment by jfmarietpro** [comment]
Thank you Keith,
I face this situation as one of our submitter requested to render his data private after there were public.
In first intent they were supposed to be public.
